export const IssueType = {
  INITIATIVE: 'INITIATIVE',
  EPIC: 'EPIC',
  STORY: 'STORY',
  FEATURE: 'FEATURE',
  TASK: 'TASK',
  IMPROVEMENT: 'IMPROVEMENT',
  BUG: 'BUG',
  INCIDENT: 'INCIDENT',
  PROBLEM: 'PROBLEM',
  CHANGE: 'CHANGE',
  REQUEST: 'REQUEST',
  SUBTASK: 'SUBTASK',
};

export const IssueStatus = {
  TODO: 'TODO',
  IN_PROGRESS: 'IN_PROGRESS',
  IN_REVIEW: 'IN_REVIEW',
  QA: 'QA',
  DONE: 'DONE',
};

export const IssuePriority = {
  HIGHEST: 'HIGHEST',
  HIGH: 'HIGH',
  MEDIUM: 'MEDIUM',
  LOW: 'LOW',
  LOWEST: 'LOWEST',
};

export const SprintStatus = {
  ACTIVE: 'ACTIVE',
  PLANNED: 'PLANNED',
  COMPLETED: 'COMPLETED',
};

export const NavigationTab = {
  MY_SPACE: 'MY_SPACE',
  DASHBOARDS: 'DASHBOARDS',
  BOARD: 'BOARD',
  BACKLOG: 'BACKLOG',
  TIMELINE: 'TIMELINE',
  ISSUES: 'ISSUES',
  REPORTS: 'REPORTS',
  RELEASES: 'RELEASES',
  AUTOMATION: 'AUTOMATION',
  AI_HUB: 'AI_HUB',
  SERVICE_ITSM: 'SERVICE_ITSM',
  ENTERPRISE_DEV: 'ENTERPRISE_DEV',
  SETTINGS: 'SETTINGS',
};
